# Generated by Django 2.0.4 on 2018-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
