# Generated by Django 2.0.4 on 2018-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_message_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
